-- Google Places Entity Type Lookup Table
-- MSSQL DDL Script
USE hhts_cleaning;
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [HHSurvey].[EntityType_purpose_lookup](
    [EntityType_id] [int] IDENTITY(1,1) NOT NULL,
    [category] [nvarchar](50) NULL,
    [EntityType] [nvarchar](100) NULL,
    [dest_purpose] [int] NULL,
PRIMARY KEY CLUSTERED 
(
    [EntityType_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO HHSurvey.EntityType_purpose_lookup (category, EntityType, dest_purpose) VALUES
-- Automotive
('Automotive', 'car_dealer', 32),
('Automotive', 'car_rental', 33),
('Automotive', 'car_repair', 33),
('Automotive', 'car_wash', 33),
('Automotive', 'electric_vehicle_charging_station', 31),
('Automotive', 'gas_station', 31),
('Automotive', 'parking', NULL),
('Automotive', 'rest_stop', NULL),

-- Business
('Business', 'corporate_office', 14),
('Business', 'farm', NULL),
('Business', 'ranch', NULL),

-- Culture
('Culture', 'art_gallery', 53),
('Culture', 'art_studio', 53),
('Culture', 'auditorium', 53),
('Culture', 'cultural_landmark', 53),
('Culture', 'historical_place', 53),
('Culture', 'monument', 53),
('Culture', 'museum', 53),
('Culture', 'performing_arts_theater', 53),
('Culture', 'sculpture', 53),

-- Education
('Education', 'library', 33),
('Education', 'preschool', 26),
('Education', 'primary_school', 21),
('Education', 'school', 21),
('Education', 'secondary_school', 21),
('Education', 'university', 22),

-- Entertainment and Recreation
('Entertainment and Recreation', 'adventure_sports_center', 53),
('Entertainment and Recreation', 'amphitheatre', 53),
('Entertainment and Recreation', 'amusement_center', 53),
('Entertainment and Recreation', 'amusement_park', 53),
('Entertainment and Recreation', 'aquarium', 53),
('Entertainment and Recreation', 'banquet_hall', 53),
('Entertainment and Recreation', 'barbecue_area', 53),
('Entertainment and Recreation', 'botanical_garden', 53),
('Entertainment and Recreation', 'bowling_alley', 53),
('Entertainment and Recreation', 'casino', 53),
('Entertainment and Recreation', 'childrens_camp', 53),
('Entertainment and Recreation', 'comedy_club', 53),
('Entertainment and Recreation', 'community_center', 53),
('Entertainment and Recreation', 'concert_hall', 53),
('Entertainment and Recreation', 'convention_center', 53),
('Entertainment and Recreation', 'cultural_center', 53),
('Entertainment and Recreation', 'cycling_park', 53),
('Entertainment and Recreation', 'dance_hall', 53),
('Entertainment and Recreation', 'dog_park', 53),
('Entertainment and Recreation', 'event_venue', 53),
('Entertainment and Recreation', 'ferris_wheel', 53),
('Entertainment and Recreation', 'garden', 53),
('Entertainment and Recreation', 'hiking_area', 53),
('Entertainment and Recreation', 'historical_landmark', 53),
('Entertainment and Recreation', 'internet_cafe', 53),
('Entertainment and Recreation', 'karaoke', 53),
('Entertainment and Recreation', 'marina', 53),
('Entertainment and Recreation', 'movie_rental', 53),
('Entertainment and Recreation', 'movie_theater', 53),
('Entertainment and Recreation', 'national_park', 53),
('Entertainment and Recreation', 'night_club', 53),
('Entertainment and Recreation', 'observation_deck', 53),
('Entertainment and Recreation', 'off_roading_area', 53),
('Entertainment and Recreation', 'opera_house', 53),
('Entertainment and Recreation', 'park', 53),
('Entertainment and Recreation', 'philharmonic_hall', 53),
('Entertainment and Recreation', 'picnic_ground', 53),
('Entertainment and Recreation', 'planetarium', 53),
('Entertainment and Recreation', 'plaza', 53),
('Entertainment and Recreation', 'roller_coaster', 53),
('Entertainment and Recreation', 'skateboard_park', 53),
('Entertainment and Recreation', 'state_park', 53),
('Entertainment and Recreation', 'tourist_attraction', 53),
('Entertainment and Recreation', 'video_arcade', 53),
('Entertainment and Recreation', 'visitor_center', 53),
('Entertainment and Recreation', 'water_park', 53),
('Entertainment and Recreation', 'wedding_venue', 53),
('Entertainment and Recreation', 'wildlife_park', 53),
('Entertainment and Recreation', 'wildlife_refuge', 53),
('Entertainment and Recreation', 'zoo', 53),

-- Facilities
('Facilities', 'public_bath', 33),
('Facilities', 'public_bathroom', 33),
('Facilities', 'stable', NULL),

-- Finance
('Finance', 'accounting', 33),
('Finance', 'atm', 33),
('Finance', 'bank', 33),

-- Food and Drink
('Food and Drink', 'acai_shop', 50),
('Food and Drink', 'afghani_restaurant', 50),
('Food and Drink', 'african_restaurant', 50),
('Food and Drink', 'american_restaurant', 50),
('Food and Drink', 'asian_restaurant', 50),
('Food and Drink', 'bagel_shop', 50),
('Food and Drink', 'bakery', 50),
('Food and Drink', 'bar', 50),
('Food and Drink', 'bar_and_grill', 50),
('Food and Drink', 'barbecue_restaurant', 50),
('Food and Drink', 'brazilian_restaurant', 50),
('Food and Drink', 'breakfast_restaurant', 50),
('Food and Drink', 'brunch_restaurant', 50),
('Food and Drink', 'buffet_restaurant', 50),
('Food and Drink', 'cafe', 50),
('Food and Drink', 'cafeteria', 50),
('Food and Drink', 'candy_store', 50),
('Food and Drink', 'cat_cafe', 50),
('Food and Drink', 'chinese_restaurant', 50),
('Food and Drink', 'chocolate_factory', 50),
('Food and Drink', 'chocolate_shop', 50),
('Food and Drink', 'coffee_shop', 50),
('Food and Drink', 'confectionery', 50),
('Food and Drink', 'deli', 50),
('Food and Drink', 'dessert_restaurant', 50),
('Food and Drink', 'dessert_shop', 50),
('Food and Drink', 'diner', 50),
('Food and Drink', 'dog_cafe', 50),
('Food and Drink', 'donut_shop', 50),
('Food and Drink', 'fast_food_restaurant', 50),
('Food and Drink', 'fine_dining_restaurant', 50),
('Food and Drink', 'food_court', 50),
('Food and Drink', 'french_restaurant', 50),
('Food and Drink', 'greek_restaurant', 50),
('Food and Drink', 'hamburger_restaurant', 50),
('Food and Drink', 'ice_cream_shop', 50),
('Food and Drink', 'indian_restaurant', 50),
('Food and Drink', 'indonesian_restaurant', 50),
('Food and Drink', 'italian_restaurant', 50),
('Food and Drink', 'japanese_restaurant', 50),
('Food and Drink', 'juice_shop', 50),
('Food and Drink', 'korean_restaurant', 50),
('Food and Drink', 'lebanese_restaurant', 50),
('Food and Drink', 'meal_delivery', 50),
('Food and Drink', 'meal_takeaway', 50),
('Food and Drink', 'mediterranean_restaurant', 50),
('Food and Drink', 'mexican_restaurant', 50),
('Food and Drink', 'middle_eastern_restaurant', 50),
('Food and Drink', 'pizza_restaurant', 50),
('Food and Drink', 'pub', 50),
('Food and Drink', 'ramen_restaurant', 50),
('Food and Drink', 'restaurant', 50),
('Food and Drink', 'sandwich_shop', 50),
('Food and Drink', 'seafood_restaurant', 50),
('Food and Drink', 'spanish_restaurant', 50),
('Food and Drink', 'steak_house', 50),
('Food and Drink', 'sushi_restaurant', 50),
('Food and Drink', 'tea_house', 50),
('Food and Drink', 'thai_restaurant', 50),
('Food and Drink', 'turkish_restaurant', 50),
('Food and Drink', 'vegan_restaurant', 50),
('Food and Drink', 'vegetarian_restaurant', 50),
('Food and Drink', 'vietnamese_restaurant', 50),
('Food and Drink', 'wine_bar', 50),

-- Government
('Government', 'city_hall', 33),
('Government', 'courthouse', 33),
('Government', 'embassy', NULL),
('Government', 'fire_station', NULL),
('Government', 'government_office', 33),
('Government', 'local_government_office', 33),
('Government', 'neighborhood', NULL),
('Government', 'police_station', NULL),
('Government', 'police', NULL),
('Government', 'post_office', 33),

-- Health and Wellness
('Health and Wellness', 'chiropractor', 34),
('Health and Wellness', 'dental_clinic', 34),
('Health and Wellness', 'dentist', 34),
('Health and Wellness', 'doctor', 34),
('Health and Wellness', 'drugstore', 32),
('Health and Wellness', 'hospital', 34),
('Health and Wellness', 'massage', 33),
('Health and Wellness', 'medical_lab', NULL),
('Health and Wellness', 'pharmacy', 34),
('Health and Wellness', 'physiotherapist', 34),
('Health and Wellness', 'sauna', 33),
('Health and Wellness', 'skin_care_clinic', 33),
('Health and Wellness', 'spa', 53),
('Health and Wellness', 'tanning_studio', 33),
('Health and Wellness', 'wellness_center', 34),
('Health and Wellness', 'yoga_studio', 51),

-- Housing
('Housing', 'apartment_building', 52),
('Housing', 'apartment_complex', 52),
('Housing', 'condominium_complex', 52),
('Housing', 'housing_complex', 52),

-- Lodging
('Lodging', 'bed_and_breakfast', 152),
('Lodging', 'budget_japanese_inn', 152),
('Lodging', 'campground', 152),
('Lodging', 'camping_cabin', 152),
('Lodging', 'cottage', 152),
('Lodging', 'extended_stay_hotel', 152),
('Lodging', 'farmstay', 152),
('Lodging', 'guest_house', 152),
('Lodging', 'hostel', 152),
('Lodging', 'hotel', 152),
('Lodging', 'inn', 152),
('Lodging', 'japanese_inn', 152),
('Lodging', 'lodging', 152),
('Lodging', 'mobile_home_park', 152),
('Lodging', 'motel', 152),
('Lodging', 'private_guest_room', 152),
('Lodging', 'resort_hotel', 152),
('Lodging', 'rv_park', 152),

-- Natural Features
('Natural Features', 'beach', NULL),

-- Places of Worship
('Places of Worship', 'church', 54),
('Places of Worship', 'hindu_temple', 54),
('Places of Worship', 'mosque', 54),
('Places of Worship', 'synagogue', 54),

-- Services
('Services', 'astrologer', 33),
('Services', 'barber_shop', 33),
('Services', 'beautician', 33),
('Services', 'beauty_salon', 33),
('Services', 'body_art_service', 33),
('Services', 'catering_service', 33),
('Services', 'cemetery', 33),
('Services', 'child_care_agency', 26),
('Services', 'consultant', 14),
('Services', 'courier_service', 33),
('Services', 'electrician', 33),
('Services', 'florist', 32),
('Services', 'food_delivery', 33),
('Services', 'foot_care', 33),
('Services', 'funeral_home', 33),
('Services', 'hair_care', 33),
('Services', 'hair_salon', 33),
('Services', 'insurance_agency', 33),
('Services', 'laundry', 33),
('Services', 'lawyer', 33),
('Services', 'locksmith', 33),
('Services', 'makeup_artist', 33),
('Services', 'moving_company', 33),
('Services', 'nail_salon', 33),
('Services', 'painter', 33),
('Services', 'plumber', 33),
('Services', 'psychic', 33),
('Services', 'real_estate_agency', 33),
('Services', 'roofing_contractor', 33),
('Services', 'storage', 33),
('Services', 'summer_camp_organizer', 33),
('Services', 'tailor', 33),
('Services', 'telecommunications_service_provider', 33),
('Services', 'tour_agency', 33),
('Services', 'tourist_information_center', 33),
('Services', 'travel_agency', 33),
('Services', 'veterinary_care', 34),

-- Shopping
('Shopping', 'asian_grocery_store', 30),
('Shopping', 'auto_parts_store', 32),
('Shopping', 'bicycle_store', 32),
('Shopping', 'book_store', 32),
('Shopping', 'butcher_shop', 30),
('Shopping', 'cell_phone_store', 32),
('Shopping', 'clothing_store', 32),
('Shopping', 'convenience_store', 30),
('Shopping', 'department_store', 32),
('Shopping', 'discount_store', 32),
('Shopping', 'electronics_store', 32),
('Shopping', 'food_store', 30),
('Shopping', 'furniture_store', 32),
('Shopping', 'gift_shop', 32),
('Shopping', 'grocery_store', 30),
('Shopping', 'hardware_store', 32),
('Shopping', 'home_goods_store', 32),
('Shopping', 'home_improvement_store', 32),
('Shopping', 'jewelry_store', 32),
('Shopping', 'liquor_store', 32),
('Shopping', 'market', 30),
('Shopping', 'pet_store', 32),
('Shopping', 'shoe_store', 32),
('Shopping', 'shopping_mall', 32),
('Shopping', 'sporting_goods_store', 32),
('Shopping', 'store', 32),
('Shopping', 'supermarket', 30),
('Shopping', 'warehouse_store', 30),
('Shopping', 'wholesaler', 32),

-- Sports
('Sports', 'arena', 53),
('Sports', 'athletic_field', 51),
('Sports', 'fishing_charter', 51),
('Sports', 'fishing_pond', NULL),
('Sports', 'fitness_center', 51),
('Sports', 'golf_course', 51),
('Sports', 'gym', 51),
('Sports', 'ice_skating_rink', 51),
('Sports', 'playground', 53),
('Sports', 'ski_resort', 51),
('Sports', 'sports_activity_location', 51),
('Sports', 'sports_club', 51),
('Sports', 'sports_coaching', 51),
('Sports', 'sports_complex', 51),
('Sports', 'stadium', 53),
('Sports', 'swimming_pool', 51),

-- Transportation
('Transportation', 'airport', 60),
('Transportation', 'airstrip', 60),
('Transportation', 'bus_station', 60),
('Transportation', 'bus_stop', 60),
('Transportation', 'ferry_terminal', 60),
('Transportation', 'heliport', 60),
('Transportation', 'international_airport', 60),
('Transportation', 'light_rail_station', 60),
('Transportation', 'park_and_ride', 60),
('Transportation', 'subway_station', 60),
('Transportation', 'taxi_stand', 60),
('Transportation', 'train_station', 60),
('Transportation', 'transit_depot', 60),
('Transportation', 'transit_station', 60),
('Transportation', 'truck_stop', 60);

-- Create index for better query performance
CREATE INDEX IX_google_entitytype_lookup_category ON HHSurvey.EntityType_purpose_lookup(category);
CREATE INDEX IX_google_entitytype_lookup_entitytype ON HHSurvey.EntityType_purpose_lookup(EntityType);
CREATE INDEX IX_google_entitytype_lookup_dest_purpose ON HHSurvey.EntityType_purpose_lookup(dest_purpose);

/*-- Query to check the results
SELECT 
    category,
    COUNT(*) as total_entries,
    COUNT(dest_purpose) as mapped_entries,
    COUNT(*) - COUNT(dest_purpose) as unmapped_entries
FROM google_entitytype_lookup 
GROUP BY category
ORDER BY category;

-- Query to show all mapped entries
SELECT * FROM google_entitytype_lookup 
WHERE dest_purpose IS NOT NULL 
ORDER BY category, EntityType;*/
