SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TYPE [HHSurvey].[TripIngredientType] AS TABLE (
    [recid] decimal(19,0) NOT NULL,
    [hhid] decimal(19,0) NOT NULL,
    [person_id] decimal(19,0) NOT NULL,
    [pernum] [int] NULL,
    [tripid] decimal(19,0) NULL,
    [tripnum] [int] NOT NULL,
    [traveldate] datetime2 NULL,
    [daynum] [int] NULL,
    [depart_time_timestamp] datetime2 NULL,
    [arrival_time_timestamp] datetime2 NULL,
    [origin_lat] [float] NULL,
    [origin_lng] [float] NULL,
    [dest_lat] [float] NULL,
    [dest_lng] [float] NULL,
    [distance_miles] [float] NULL,
    [travel_time] float NULL,
    [hhmember1] decimal(19,0) NULL,
    [hhmember2] decimal(19,0) NULL,
    [hhmember3] decimal(19,0) NULL,
    [hhmember4] decimal(19,0) NULL,
    [hhmember5] decimal(19,0) NULL,
    [hhmember6] decimal(19,0) NULL,
    [hhmember7] decimal(19,0) NULL,
    [hhmember8] decimal(19,0) NULL,
    [hhmember9] decimal(19,0) NULL,
    [hhmember10] decimal(19,0) NULL,
    [hhmember11] decimal(19,0) NULL,
    [hhmember12] decimal(19,0) NULL,
    [hhmember13] decimal(19,0) NULL,
    [travelers_hh] [int] NULL,
    [travelers_nonhh] [int] NULL,
    [travelers_total] [int] NULL,
    [origin_purpose] [int] NULL,
    [dest_purpose] [int] NULL,
    [dest_purpose_other] nvarchar(255) NULL,
    [mode_1] int NULL,
    [mode_2] int NULL,
    [mode_3] int NULL,
    [mode_4] int NULL,
    [driver] int NULL,
    [mode_acc] int NULL,
    [mode_egr] int NULL,
    [speed_mph] [float] NULL,
    [mode_other_specify] nvarchar(1000) NULL,
    [origin_geog] GEOGRAPHY NULL,
    [dest_geog] GEOGRAPHY NULL,
    [dest_is_home] bit NULL,
    [dest_is_work] bit NULL,
    [modes] nvarchar(255) NULL,
    [psrc_inserted] bit NULL,
    [revision_code] nvarchar(255) NULL,
    [psrc_resolved] int NULL,
    [psrc_comment] nvarchar(255) NULL,
    [trip_link] int NOT NULL
);
GO