CREATE TABLE [dbo].[trip_plus]
(
[record_id] [bigint] NULL,
[hhid] [int] NOT NULL,
[travel_date] [date] NULL,
[trip_id] [bigint] NOT NULL,
[index] [bigint] NULL,
[person_num] [tinyint] NULL,
[person_id] [bigint] NULL,
[day_num] [tinyint] NULL,
[day_id] [bigint] NULL,
[tripnum] [tinyint] NULL,
[depart_date] [date] NULL,
[depart_hour] [int] NULL,
[depart_minute] [int] NULL,
[depart_seconds] [int] NULL,
[arrive_date] [date] NULL,
[arrive_hour] [int] NULL,
[arrive_minute] [int] NULL,
[arrive_second] [int] NULL,
[o_puma_2012] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_bg_2020] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_lon] [decimal] (18, 10) NULL,
[o_lat] [decimal] (18, 10) NULL,
[d_puma_2012] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_bg_2020] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_lon] [decimal] (18, 10) NULL,
[d_lat] [decimal] (18, 10) NULL,
[distance_meters] [decimal] (18, 10) NULL,
[distance_miles] [decimal] (18, 10) NULL,
[duration_minutes] [int] NULL,
[duration_seconds] [int] NULL,
[speed_mph] [decimal] (18, 10) NULL,
[dwell_mins] [decimal] (18, 10) NULL,
[origin_label] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_purpose_other] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dest_label] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mode_other_specify] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxi_cost] [smallint] NULL,
[pt_density] [decimal] (18, 10) NULL,
[point_dist_index] [decimal] (18, 10) NULL,
[trip_weight] [decimal] (18, 10) NULL,
[survey_year] [smallint] NULL,
[day_is_complete_a] [smallint] NULL,
[day_is_complete_b] [smallint] NULL,
[hh_day_iscomplete_a] [smallint] NULL,
[hh_day_iscomplete_b] [smallint] NULL,
[travel_day] [smallint] NULL,
[travel_dow] [smallint] NULL,
[day_is_complete] [smallint] NULL,
[depart_dow] [smallint] NULL,
[arrive_dow] [smallint] NULL,
[o_in_region] [smallint] NULL,
[d_in_region] [smallint] NULL,
[speed_flag] [smallint] NULL,
[days_first_trip] [smallint] NULL,
[days_last_trip] [smallint] NULL,
[o_purpose_category] [smallint] NULL,
[o_purpose] [smallint] NULL,
[d_purpose_category] [smallint] NULL,
[d_purpose] [smallint] NULL,
[mode_type] [smallint] NULL,
[mode_1] [smallint] NULL,
[mode_2] [smallint] NULL,
[mode_3] [smallint] NULL,
[mode_4] [smallint] NULL,
[is_transit] [smallint] NULL,
[is_access] [smallint] NULL,
[is_egress] [smallint] NULL,
[has_access] [smallint] NULL,
[has_egress] [smallint] NULL,
[transit_access] [smallint] NULL,
[transit_egress] [smallint] NULL,
[num_travelers] [smallint] NULL,
[num_hh_travelers] [smallint] NULL,
[num_non_hh_travelers] [smallint] NULL,
[hh_member_1] [int] NULL,
[hh_member_2] [int] NULL,
[hh_member_3] [int] NULL,
[hh_member_4] [int] NULL,
[hh_member_5] [int] NULL,
[hh_member_6] [int] NULL,
[hh_member_7] [int] NULL,
[hh_member_8] [int] NULL,
[hh_member_9] [int] NULL,
[hh_member_10] [int] NULL,
[hh_member_11] [int] NULL,
[hh_member_12] [int] NULL,
[driver] [smallint] NULL,
[change_vehicles] [smallint] NULL,
[taxi_pay] [smallint] NULL,
[analyst_split] [smallint] NULL,
[analyst_merge] [smallint] NULL,
[split_loop] [smallint] NULL,
[copied_from_proxy] [smallint] NULL,
[user_split] [smallint] NULL,
[user_merged] [smallint] NULL,
[added_type] [smallint] NULL,
[teleport] [smallint] NULL,
[trace_quality_flag] [smallint] NULL,
[joint_trip_num] [smallint] NULL,
[joint_trip_id] [bigint] NULL,
[corrected_hh_members] [smallint] NULL,
[depart_time] [datetime2] NULL,
[arrive_time] [datetime2] NULL,
[imputed_record_type] [smallint] NULL,
[imputed_host_trip] [bigint] NULL,
[imputed_joint_trip] [bigint] NULL,
[svy_complete] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hh_day_iscomplete] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_num] [smallint] NULL
) ON [PRIMARY]
GO
