CREATE TABLE [HHSurvey].[PUDO_purposes]
(
[purpose_id] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [HHSurvey].[PUDO_purposes] ADD CONSTRAINT [PK__PUDO_pur__8ED1FDD8F4CA446F] PRIMARY KEY CLUSTERED ([purpose_id]) ON [PRIMARY]
GO
