CREATE TABLE [History].[HHSurvey__trip_ingredients_done]
(
[ingredient_id] [int] NOT NULL,
[recid] [decimal] (18, 0) NOT NULL,
[hhid] [decimal] (18, 0) NOT NULL,
[person_id] [decimal] (18, 0) NOT NULL,
[pernum] [int] NULL,
[tripid] [decimal] (18, 0) NULL,
[tripnum] [int] NOT NULL,
[traveldate] [datetime2] NULL,
[daynum] [int] NULL,
[depart_time_timestamp] [datetime2] NULL,
[arrival_time_timestamp] [datetime2] NULL,
[origin_lat] [float] NULL,
[origin_lng] [float] NULL,
[dest_lat] [float] NULL,
[dest_lng] [float] NULL,
[distance_miles] [float] NULL,
[travel_time] [float] NULL,
[hhmember1] [decimal] (18, 0) NULL,
[hhmember2] [decimal] (18, 0) NULL,
[hhmember3] [decimal] (18, 0) NULL,
[hhmember4] [decimal] (18, 0) NULL,
[hhmember5] [decimal] (18, 0) NULL,
[hhmember6] [decimal] (18, 0) NULL,
[hhmember7] [decimal] (18, 0) NULL,
[hhmember8] [decimal] (18, 0) NULL,
[hhmember9] [decimal] (18, 0) NULL,
[hhmember10] [decimal] (18, 0) NULL,
[hhmember11] [decimal] (18, 0) NULL,
[hhmember12] [decimal] (18, 0) NULL,
[hhmember13] [decimal] (18, 0) NULL,
[travelers_hh] [int] NOT NULL,
[travelers_nonhh] [int] NOT NULL,
[travelers_total] [int] NOT NULL,
[origin_purpose] [int] NULL,
[dest_purpose] [int] NULL,
[dest_purpose_other] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mode_1] [int] NULL,
[mode_2] [int] NULL,
[mode_3] [int] NULL,
[mode_4] [int] NULL,
[driver] [smallint] NULL,
[mode_acc] [smallint] NULL,
[mode_egr] [smallint] NULL,
[speed_mph] [float] NULL,
[mode_other_specify] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[origin_geog] [sys].[geography] NULL,
[dest_geog] [sys].[geography] NULL,
[dest_is_home] [bit] NULL,
[dest_is_work] [bit] NULL,
[modes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_inserted] [bit] NULL,
[revision_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_resolved] [smallint] NULL,
[psrc_comment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_link] [int] NULL,
[valid_from] [datetime2] NOT NULL,
[valid_to] [datetime2] NOT NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [ix_HHSurvey__trip_ingredients_done] ON [History].[HHSurvey__trip_ingredients_done] ([valid_to], [valid_from]) ON [PRIMARY]
GO
CREATE TABLE [HHSurvey].[trip_ingredients_done]
(
[ingredient_id] [int] NOT NULL IDENTITY(1, 1),
[recid] [decimal] (18, 0) NOT NULL,
[hhid] [decimal] (18, 0) NOT NULL,
[person_id] [decimal] (18, 0) NOT NULL,
[pernum] [int] NULL,
[tripid] [decimal] (18, 0) NULL,
[tripnum] [int] NOT NULL,
[traveldate] [datetime2] NULL,
[daynum] [int] NULL,
[depart_time_timestamp] [datetime2] NULL,
[arrival_time_timestamp] [datetime2] NULL,
[origin_lat] [float] NULL,
[origin_lng] [float] NULL,
[dest_lat] [float] NULL,
[dest_lng] [float] NULL,
[distance_miles] [float] NULL,
[travel_time] [float] NULL,
[hhmember1] [decimal] (18, 0) NULL,
[hhmember2] [decimal] (18, 0) NULL,
[hhmember3] [decimal] (18, 0) NULL,
[hhmember4] [decimal] (18, 0) NULL,
[hhmember5] [decimal] (18, 0) NULL,
[hhmember6] [decimal] (18, 0) NULL,
[hhmember7] [decimal] (18, 0) NULL,
[hhmember8] [decimal] (18, 0) NULL,
[hhmember9] [decimal] (18, 0) NULL,
[hhmember10] [decimal] (18, 0) NULL,
[hhmember11] [decimal] (18, 0) NULL,
[hhmember12] [decimal] (18, 0) NULL,
[hhmember13] [decimal] (18, 0) NULL,
[travelers_hh] [int] NOT NULL,
[travelers_nonhh] [int] NOT NULL,
[travelers_total] [int] NOT NULL,
[origin_purpose] [int] NULL,
[dest_purpose] [int] NULL,
[dest_purpose_other] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mode_1] [int] NULL,
[mode_2] [int] NULL,
[mode_3] [int] NULL,
[mode_4] [int] NULL,
[driver] [smallint] NULL,
[mode_acc] [smallint] NULL,
[mode_egr] [smallint] NULL,
[speed_mph] [float] NULL,
[mode_other_specify] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[origin_geog] [sys].[geography] NULL,
[dest_geog] [sys].[geography] NULL,
[dest_is_home] [bit] NULL,
[dest_is_work] [bit] NULL,
[modes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_inserted] [bit] NULL,
[revision_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_resolved] [smallint] NULL,
[psrc_comment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trip_link] [int] NULL,
[valid_from] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [HHSurvey_trip_ingredients_done_valid_from_default] DEFAULT (sysutcdatetime()),
[valid_to] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [HHSurvey_trip_ingredients_done_valid_to_default] DEFAULT ('9999-12-31 23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (valid_from, valid_to),
CONSTRAINT [PK_trip_ingredients_done] PRIMARY KEY CLUSTERED ([ingredient_id]) ON [PRIMARY]
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [History].[HHSurvey__trip_ingredients_done])
)
GO
