CREATE TABLE [History].[HHSurvey__Person]
(
[ethnicity_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hhid] [float] NULL,
[industry_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_trips] [float] NULL,
[numdayscomplete] [float] NULL,
[pernum] [float] NULL,
[person_id] [decimal] (19, 0) NOT NULL,
[person_weight] [float] NULL,
[race_other_specify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_bg] [float] NULL,
[school_loc_lat] [float] NULL,
[school_loc_lng] [float] NULL,
[school_puma10] [float] NULL,
[second_home_lat] [float] NULL,
[second_home_lon] [float] NULL,
[survey_year] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_bg] [float] NULL,
[work_lat] [float] NULL,
[work_lng] [float] NULL,
[work_puma10] [float] NULL,
[age_detailed] [float] NULL,
[bike_freq] [float] NULL,
[carshare_freq] [float] NULL,
[commute_freq] [float] NULL,
[commute_subsidy_1] [float] NULL,
[commute_subsidy_2] [float] NULL,
[commute_subsidy_3] [float] NULL,
[commute_subsidy_4] [float] NULL,
[commute_subsidy_5] [float] NULL,
[commute_subsidy_6] [float] NULL,
[commute_subsidy_7] [float] NULL,
[commute_subsidy_996] [float] NULL,
[commute_subsidy_998] [float] NULL,
[commute_subsidy_use_1] [float] NULL,
[commute_subsidy_use_2] [float] NULL,
[commute_subsidy_use_3] [float] NULL,
[commute_subsidy_use_4] [float] NULL,
[commute_subsidy_use_5] [float] NULL,
[commute_subsidy_use_6] [float] NULL,
[commute_subsidy_use_7] [float] NULL,
[commute_subsidy_use_996] [float] NULL,
[disability_person] [float] NULL,
[education] [float] NULL,
[employment] [float] NULL,
[ethnicity_1] [float] NULL,
[ethnicity_2] [float] NULL,
[ethnicity_3] [float] NULL,
[ethnicity_4] [float] NULL,
[ethnicity_997] [float] NULL,
[ethnicity_999] [float] NULL,
[ev_typical_charge_1] [float] NULL,
[ev_typical_charge_2] [float] NULL,
[ev_typical_charge_3] [float] NULL,
[ev_typical_charge_4] [float] NULL,
[ev_typical_charge_5] [float] NULL,
[ev_typical_charge_6] [float] NULL,
[ev_typical_charge_997] [float] NULL,
[gender] [float] NULL,
[hh_is_complete] [float] NULL,
[hours_work] [float] NULL,
[industry] [float] NULL,
[is_participant] [float] NULL,
[license] [float] NULL,
[mobility_aides] [float] NULL,
[office_available] [float] NULL,
[participate] [float] NULL,
[person_is_complete] [float] NULL,
[proxy] [float] NULL,
[proxy_parent] [float] NULL,
[race_afam] [float] NULL,
[race_aiak] [float] NULL,
[race_asian] [float] NULL,
[race_hapi] [float] NULL,
[race_noanswer] [float] NULL,
[race_other] [float] NULL,
[race_white] [float] NULL,
[relationship] [float] NULL,
[remote_class_freq] [float] NULL,
[school_freq] [float] NULL,
[school_in_region] [float] NULL,
[school_mode_typical] [float] NULL,
[schooltype] [float] NULL,
[second_home] [float] NULL,
[second_home_in_region] [float] NULL,
[sexuality] [float] NULL,
[share_1] [float] NULL,
[share_2] [float] NULL,
[share_3] [float] NULL,
[share_4] [float] NULL,
[share_5] [float] NULL,
[share_996] [float] NULL,
[smartphone_type] [float] NULL,
[student] [float] NULL,
[surveyable] [float] NULL,
[telecommute_freq] [float] NULL,
[tnc_freq] [float] NULL,
[transit_freq] [float] NULL,
[walk_freq] [float] NULL,
[work_in_region] [float] NULL,
[work_mode] [float] NULL,
[workplace] [float] NULL,
[drive_for_work] [float] NULL,
[employment_followup] [float] NULL,
[paid_work] [float] NULL,
[return_from_leave] [float] NULL,
[transportation_statement_car] [float] NULL,
[transportation_statement_environ] [float] NULL,
[transportation_statement_retail] [float] NULL,
[transportation_statement_telework] [float] NULL,
[transportation_statement_transit] [float] NULL,
[transportation_statement_travel] [float] NULL,
[transportation_statement_walk] [float] NULL,
[work_from_home] [float] NULL,
[work_geog] [sys].[geography] NULL,
[school_geog] [sys].[geography] NULL,
[valid_from] [datetime2] NOT NULL,
[valid_to] [datetime2] NOT NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [ix_HHSurvey__Person] ON [History].[HHSurvey__Person] ([valid_to], [valid_from]) ON [PRIMARY]
GO
CREATE TABLE [HHSurvey].[Person]
(
[ethnicity_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hhid] [float] NULL,
[industry_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_trips] [float] NULL,
[numdayscomplete] [float] NULL,
[pernum] [float] NULL,
[person_id] [decimal] (19, 0) NOT NULL,
[person_weight] [float] NULL,
[race_other_specify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_bg] [float] NULL,
[school_loc_lat] [float] NULL,
[school_loc_lng] [float] NULL,
[school_puma10] [float] NULL,
[second_home_lat] [float] NULL,
[second_home_lon] [float] NULL,
[survey_year] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_bg] [float] NULL,
[work_lat] [float] NULL,
[work_lng] [float] NULL,
[work_puma10] [float] NULL,
[age_detailed] [float] NULL,
[bike_freq] [float] NULL,
[carshare_freq] [float] NULL,
[commute_freq] [float] NULL,
[commute_subsidy_1] [float] NULL,
[commute_subsidy_2] [float] NULL,
[commute_subsidy_3] [float] NULL,
[commute_subsidy_4] [float] NULL,
[commute_subsidy_5] [float] NULL,
[commute_subsidy_6] [float] NULL,
[commute_subsidy_7] [float] NULL,
[commute_subsidy_996] [float] NULL,
[commute_subsidy_998] [float] NULL,
[commute_subsidy_use_1] [float] NULL,
[commute_subsidy_use_2] [float] NULL,
[commute_subsidy_use_3] [float] NULL,
[commute_subsidy_use_4] [float] NULL,
[commute_subsidy_use_5] [float] NULL,
[commute_subsidy_use_6] [float] NULL,
[commute_subsidy_use_7] [float] NULL,
[commute_subsidy_use_996] [float] NULL,
[disability_person] [float] NULL,
[education] [float] NULL,
[employment] [float] NULL,
[ethnicity_1] [float] NULL,
[ethnicity_2] [float] NULL,
[ethnicity_3] [float] NULL,
[ethnicity_4] [float] NULL,
[ethnicity_997] [float] NULL,
[ethnicity_999] [float] NULL,
[ev_typical_charge_1] [float] NULL,
[ev_typical_charge_2] [float] NULL,
[ev_typical_charge_3] [float] NULL,
[ev_typical_charge_4] [float] NULL,
[ev_typical_charge_5] [float] NULL,
[ev_typical_charge_6] [float] NULL,
[ev_typical_charge_997] [float] NULL,
[gender] [float] NULL,
[hh_is_complete] [float] NULL,
[hours_work] [float] NULL,
[industry] [float] NULL,
[is_participant] [float] NULL,
[license] [float] NULL,
[mobility_aides] [float] NULL,
[office_available] [float] NULL,
[participate] [float] NULL,
[person_is_complete] [float] NULL,
[proxy] [float] NULL,
[proxy_parent] [float] NULL,
[race_afam] [float] NULL,
[race_aiak] [float] NULL,
[race_asian] [float] NULL,
[race_hapi] [float] NULL,
[race_noanswer] [float] NULL,
[race_other] [float] NULL,
[race_white] [float] NULL,
[relationship] [float] NULL,
[remote_class_freq] [float] NULL,
[school_freq] [float] NULL,
[school_in_region] [float] NULL,
[school_mode_typical] [float] NULL,
[schooltype] [float] NULL,
[second_home] [float] NULL,
[second_home_in_region] [float] NULL,
[sexuality] [float] NULL,
[share_1] [float] NULL,
[share_2] [float] NULL,
[share_3] [float] NULL,
[share_4] [float] NULL,
[share_5] [float] NULL,
[share_996] [float] NULL,
[smartphone_type] [float] NULL,
[student] [float] NULL,
[surveyable] [float] NULL,
[telecommute_freq] [float] NULL,
[tnc_freq] [float] NULL,
[transit_freq] [float] NULL,
[walk_freq] [float] NULL,
[work_in_region] [float] NULL,
[work_mode] [float] NULL,
[workplace] [float] NULL,
[drive_for_work] [float] NULL,
[employment_followup] [float] NULL,
[paid_work] [float] NULL,
[return_from_leave] [float] NULL,
[transportation_statement_car] [float] NULL,
[transportation_statement_environ] [float] NULL,
[transportation_statement_retail] [float] NULL,
[transportation_statement_telework] [float] NULL,
[transportation_statement_transit] [float] NULL,
[transportation_statement_travel] [float] NULL,
[transportation_statement_walk] [float] NULL,
[work_from_home] [float] NULL,
[work_geog] [sys].[geography] NULL,
[school_geog] [sys].[geography] NULL,
[valid_from] [datetime2] GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [HHSurvey_Person_valid_from_default] DEFAULT (sysutcdatetime()),
[valid_to] [datetime2] GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [HHSurvey_Person_valid_to_default] DEFAULT ('9999-12-31 23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (valid_from, valid_to),
CONSTRAINT [PK_person_id] PRIMARY KEY CLUSTERED ([person_id]) WITH (FILLFACTOR=80) ON [PRIMARY]
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [History].[HHSurvey__Person])
)
GO
CREATE SPATIAL INDEX [work_geog_idx] ON [HHSurvey].[Person] ([work_geog]) WITH (CELLS_PER_OBJECT = 12) ON [PRIMARY]
GO
