CREATE TABLE [HHSurvey].[removed_trip]
(
[recid] [int] NOT NULL,
[hhid] [decimal] (19, 0) NOT NULL,
[person_id] [decimal] (19, 0) NOT NULL,
[pernum] [int] NULL,
[tripid] [decimal] (19, 0) NULL,
[tripnum] [int] NOT NULL,
[traveldate] [datetime2] NULL,
[daynum] [int] NULL,
[depart_time_timestamp] [datetime2] NULL,
[arrival_time_timestamp] [datetime2] NULL,
[origin_lat] [float] NULL,
[origin_lng] [float] NULL,
[dest_lat] [float] NULL,
[dest_lng] [float] NULL,
[distance_miles] [float] NULL,
[travel_time] [float] NULL,
[hhmember1] [decimal] (19, 0) NULL,
[hhmember2] [decimal] (19, 0) NULL,
[hhmember3] [decimal] (19, 0) NULL,
[hhmember4] [decimal] (19, 0) NULL,
[hhmember5] [decimal] (19, 0) NULL,
[hhmember6] [decimal] (19, 0) NULL,
[hhmember7] [decimal] (19, 0) NULL,
[hhmember8] [decimal] (19, 0) NULL,
[hhmember9] [decimal] (19, 0) NULL,
[hhmember10] [decimal] (19, 0) NOT NULL,
[hhmember11] [decimal] (19, 0) NOT NULL,
[hhmember12] [decimal] (19, 0) NOT NULL,
[hhmember13] [decimal] (19, 0) NOT NULL,
[travelers_hh] [int] NOT NULL,
[travelers_nonhh] [int] NOT NULL,
[travelers_total] [int] NOT NULL,
[origin_purpose] [int] NULL,
[dest_purpose] [int] NULL,
[dest_purpose_other] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mode_1] [smallint] NOT NULL,
[mode_2] [smallint] NULL,
[mode_3] [smallint] NULL,
[mode_4] [smallint] NULL,
[driver] [smallint] NULL,
[mode_acc] [smallint] NULL,
[mode_egr] [smallint] NULL,
[speed_mph] [float] NULL,
[day_id] [bigint] NOT NULL,
[mode_other_specify] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[origin_geog] [sys].[geography] NULL,
[dest_geog] [sys].[geography] NULL,
[dest_county] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dest_city] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dest_zip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dest_is_home] [bit] NULL,
[dest_is_work] [bit] NULL,
[modes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_inserted] [bit] NULL,
[revision_code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psrc_resolved] [smallint] NULL,
[psrc_comment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
