CREATE TABLE [HHSurvey].[Day]
(
[day_id] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[daynum] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hhid] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_complete_trip_surveys] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_trips] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pernum] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_id] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[survey_year] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[travel_date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attend_school_1] [int] NULL,
[attend_school_2] [int] NULL,
[attend_school_3] [int] NULL,
[attend_school_998] [int] NULL,
[attend_school_999] [int] NULL,
[day_iscomplete] [int] NULL,
[deliver_elsewhere] [int] NULL,
[deliver_food] [int] NULL,
[deliver_grocery] [int] NULL,
[deliver_none] [int] NULL,
[deliver_office] [int] NULL,
[deliver_other] [int] NULL,
[deliver_package] [int] NULL,
[deliver_work] [int] NULL,
[hh_day_iscomplete] [int] NULL,
[is_participant] [int] NULL,
[loc_end] [int] NULL,
[loc_start] [int] NULL,
[proxy_complete] [int] NULL,
[summary_complete] [int] NULL,
[surveyable] [int] NULL,
[telework_time] [int] NULL,
[travel_day] [int] NULL,
[travel_dow] [int] NULL,
[no_travel] [int] NULL
) ON [PRIMARY]
GO
