CREATE TABLE [History].[HHSurvey__Person]
(
[ethnicity_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hhid] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[industry_other] [varchar] (356) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[can_drive] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_trips] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numdayscomplete] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pernum] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_id] [decimal] (19, 0) NOT NULL,
[race_other_specify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_bg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_loc_lat] [float] NULL,
[school_loc_lng] [float] NULL,
[school_puma10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[second_home_lat] [float] NULL,
[second_home_lon] [float] NULL,
[survey_year] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_bg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_lat] [float] NULL,
[work_lng] [float] NULL,
[work_puma10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bike_freq] [int] NULL,
[carshare_freq] [int] NULL,
[commute_freq] [int] NULL,
[commute_subsidy_1] [int] NULL,
[commute_subsidy_2] [int] NULL,
[commute_subsidy_3] [int] NULL,
[commute_subsidy_4] [int] NULL,
[commute_subsidy_5] [int] NULL,
[commute_subsidy_6] [int] NULL,
[commute_subsidy_7] [int] NULL,
[commute_subsidy_996] [int] NULL,
[commute_subsidy_998] [int] NULL,
[commute_subsidy_use_1] [int] NULL,
[commute_subsidy_use_2] [int] NULL,
[commute_subsidy_use_3] [int] NULL,
[commute_subsidy_use_4] [int] NULL,
[commute_subsidy_use_5] [int] NULL,
[commute_subsidy_use_6] [int] NULL,
[commute_subsidy_use_7] [int] NULL,
[commute_subsidy_use_996] [int] NULL,
[disability_person] [int] NULL,
[education] [int] NULL,
[employment] [int] NULL,
[ethnicity_1] [int] NULL,
[ethnicity_2] [int] NULL,
[ethnicity_3] [int] NULL,
[ethnicity_4] [int] NULL,
[ethnicity_997] [int] NULL,
[ethnicity_999] [int] NULL,
[ev_typical_charge_1] [int] NULL,
[ev_typical_charge_2] [int] NULL,
[ev_typical_charge_3] [int] NULL,
[ev_typical_charge_4] [int] NULL,
[ev_typical_charge_5] [int] NULL,
[ev_typical_charge_6] [int] NULL,
[ev_typical_charge_997] [int] NULL,
[gender] [int] NULL,
[hours_work] [int] NULL,
[industry] [int] NULL,
[is_participant] [int] NULL,
[mobility_aides] [int] NULL,
[office_available] [int] NULL,
[participate] [int] NULL,
[person_is_complete] [int] NULL,
[proxy] [int] NULL,
[proxy_parent] [int] NULL,
[race_afam] [int] NULL,
[race_aiak] [int] NULL,
[race_asian] [int] NULL,
[race_hapi] [int] NULL,
[race_noanswer] [int] NULL,
[race_other] [int] NULL,
[race_white] [int] NULL,
[relationship] [int] NULL,
[remote_class_freq] [int] NULL,
[school_freq] [int] NULL,
[school_in_region] [int] NULL,
[school_mode_typical] [int] NULL,
[schooltype] [int] NULL,
[second_home] [int] NULL,
[second_home_in_region] [int] NULL,
[sexuality] [int] NULL,
[share_1] [int] NULL,
[share_2] [int] NULL,
[share_3] [int] NULL,
[share_4] [int] NULL,
[share_5] [int] NULL,
[share_996] [int] NULL,
[smartphone_type] [int] NULL,
[student] [int] NULL,
[surveyable] [int] NULL,
[telecommute_freq] [int] NULL,
[tnc_freq] [int] NULL,
[transit_freq] [int] NULL,
[walk_freq] [int] NULL,
[work_in_region] [int] NULL,
[work_mode] [int] NULL,
[workplace] [int] NULL,
[age_detailed] [int] NULL,
[drive_for_work] [int] NULL,
[employment_followup] [int] NULL,
[paid_work] [int] NULL,
[return_from_leave] [int] NULL,
[transportation_statement_car] [int] NULL,
[transportation_statement_environ] [int] NULL,
[transportation_statement_retail] [int] NULL,
[transportation_statement_telework] [float] NULL,
[transportation_statement_transit] [int] NULL,
[transportation_statement_travel] [int] NULL,
[transportation_statement_walk] [int] NULL,
[work_from_home] [int] NULL,
[work_geog] [sys].[geography] NULL,
[school_geog] [sys].[geography] NULL,
[valid_from] [datetime2] NOT NULL,
[valid_to] [datetime2] NOT NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [ix_HHSurvey__Person] ON [History].[HHSurvey__Person] ([valid_to], [valid_from]) ON [PRIMARY]
GO
CREATE TABLE [HHSurvey].[Person]
(
[ethnicity_other] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hhid] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[industry_other] [varchar] (356) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[can_drive] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_trips] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numdayscomplete] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pernum] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[person_id] [decimal] (19, 0) NOT NULL,
[race_other_specify] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_bg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school_loc_lat] [float] NULL,
[school_loc_lng] [float] NULL,
[school_puma10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[second_home_lat] [float] NULL,
[second_home_lon] [float] NULL,
[survey_year] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_bg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_lat] [float] NULL,
[work_lng] [float] NULL,
[work_puma10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bike_freq] [int] NULL,
[carshare_freq] [int] NULL,
[commute_freq] [int] NULL,
[commute_subsidy_1] [int] NULL,
[commute_subsidy_2] [int] NULL,
[commute_subsidy_3] [int] NULL,
[commute_subsidy_4] [int] NULL,
[commute_subsidy_5] [int] NULL,
[commute_subsidy_6] [int] NULL,
[commute_subsidy_7] [int] NULL,
[commute_subsidy_996] [int] NULL,
[commute_subsidy_998] [int] NULL,
[commute_subsidy_use_1] [int] NULL,
[commute_subsidy_use_2] [int] NULL,
[commute_subsidy_use_3] [int] NULL,
[commute_subsidy_use_4] [int] NULL,
[commute_subsidy_use_5] [int] NULL,
[commute_subsidy_use_6] [int] NULL,
[commute_subsidy_use_7] [int] NULL,
[commute_subsidy_use_996] [int] NULL,
[disability_person] [int] NULL,
[education] [int] NULL,
[employment] [int] NULL,
[ethnicity_1] [int] NULL,
[ethnicity_2] [int] NULL,
[ethnicity_3] [int] NULL,
[ethnicity_4] [int] NULL,
[ethnicity_997] [int] NULL,
[ethnicity_999] [int] NULL,
[ev_typical_charge_1] [int] NULL,
[ev_typical_charge_2] [int] NULL,
[ev_typical_charge_3] [int] NULL,
[ev_typical_charge_4] [int] NULL,
[ev_typical_charge_5] [int] NULL,
[ev_typical_charge_6] [int] NULL,
[ev_typical_charge_997] [int] NULL,
[gender] [int] NULL,
[hours_work] [int] NULL,
[industry] [int] NULL,
[is_participant] [int] NULL,
[mobility_aides] [int] NULL,
[office_available] [int] NULL,
[participate] [int] NULL,
[person_is_complete] [int] NULL,
[proxy] [int] NULL,
[proxy_parent] [int] NULL,
[race_afam] [int] NULL,
[race_aiak] [int] NULL,
[race_asian] [int] NULL,
[race_hapi] [int] NULL,
[race_noanswer] [int] NULL,
[race_other] [int] NULL,
[race_white] [int] NULL,
[relationship] [int] NULL,
[remote_class_freq] [int] NULL,
[school_freq] [int] NULL,
[school_in_region] [int] NULL,
[school_mode_typical] [int] NULL,
[schooltype] [int] NULL,
[second_home] [int] NULL,
[second_home_in_region] [int] NULL,
[sexuality] [int] NULL,
[share_1] [int] NULL,
[share_2] [int] NULL,
[share_3] [int] NULL,
[share_4] [int] NULL,
[share_5] [int] NULL,
[share_996] [int] NULL,
[smartphone_type] [int] NULL,
[student] [int] NULL,
[surveyable] [int] NULL,
[telecommute_freq] [int] NULL,
[tnc_freq] [int] NULL,
[transit_freq] [int] NULL,
[walk_freq] [int] NULL,
[work_in_region] [int] NULL,
[work_mode] [int] NULL,
[workplace] [int] NULL,
[age_detailed] [int] NULL,
[drive_for_work] [int] NULL,
[employment_followup] [int] NULL,
[paid_work] [int] NULL,
[return_from_leave] [int] NULL,
[transportation_statement_car] [int] NULL,
[transportation_statement_environ] [int] NULL,
[transportation_statement_retail] [int] NULL,
[transportation_statement_telework] [float] NULL,
[transportation_statement_transit] [int] NULL,
[transportation_statement_travel] [int] NULL,
[transportation_statement_walk] [int] NULL,
[work_from_home] [int] NULL,
[work_geog] [sys].[geography] NULL,
[school_geog] [sys].[geography] NULL,
[valid_from] [datetime2] GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [HHSurvey_Person_valid_from_default] DEFAULT (sysutcdatetime()),
[valid_to] [datetime2] GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [HHSurvey_Person_valid_to_default] DEFAULT ('9999-12-31 23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (valid_from, valid_to),
CONSTRAINT [PK_person_id] PRIMARY KEY CLUSTERED ([person_id]) WITH (FILLFACTOR=80) ON [PRIMARY]
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [History].[HHSurvey__Person])
)
GO
CREATE SPATIAL INDEX [work_geog_idx] ON [HHSurvey].[Person] ([work_geog]) WITH (CELLS_PER_OBJECT = 12) ON [PRIMARY]
GO
